//! Sensor identity, kind, and calibration metadata.
//!
//! Every observation in the substrate carries a `SensorId` — the identity
//! of the producer that emitted it — and a [`Calibration`] — the producer's
//! self-assessment of whether its output is trustworthy. Calibration is the
//! load-bearing concept: an *uncalibrated* observation is not "wrong", it is
//! *not yet trusted*. Pneuma uses calibration to decide whether to route
//! through clarification or proceed.
//!
//! ## Why per-observation calibration
//!
//! Calibration is not constant within a session. A gaze tracker may be well
//! calibrated when the user is sitting still, then drift after they shift
//! posture. The substrate design forces every token to declare its
//! calibration *at emission time*. Pneuma's confidence score is then a
//! function of token-level calibration plus join-confidence; this matches
//! the `pneuma-core::confidence::ConfidenceScore::is_calibrated` model.
//!
//! ## The `is_calibrated` semantics, made explicit
//!
//! From `MIL-PROJECT.md` §10.2:
//!
//! > Uncalibrated scores get a 20% effective penalty against thresholds.
//!
//! The substrate does not apply that penalty — Pneuma does. The substrate's
//! job is to *honestly report* the calibration status. Producers must not
//! lie about calibration to lower the threshold.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::time::Timestamp;

// --- SensorId ----------------------------------------------------------------

/// Stable identity of a producer instance.
///
/// `UUIDv7` — sortable by creation time, useful for journal replay. Sensor
/// instances mint a fresh ID on construction; the ID survives across
/// recalibration but not across process restart.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SensorId(Uuid);

impl SensorId {
    /// Mint a fresh `UUIDv7`-backed sensor identity.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::now_v7())
    }

    /// Wrap an existing `Uuid`. Used by replay machinery and tests.
    #[must_use]
    pub fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    /// Inner UUID, for callers needing to bridge to other ID systems.
    #[must_use]
    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl Default for SensorId {
    fn default() -> Self {
        Self::new()
    }
}

// --- SensorKind --------------------------------------------------------------

/// What the sensor observes.
///
/// Used for routing (the `pneuma-router` selects compatible producers per
/// primitive) and for diagnostic display. Adding a new variant is a
/// **non-breaking change** because of `#[non_exhaustive]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SensorKind {
    /// The workspace observer — files, windows, apps, selections, cursor.
    /// Drives the [`crate::workspace::WorkspaceContext`] substrate.
    Workspace,
    /// Vision-based hand tracker (`MediaPipe` / `WiLoR` / `HaMeR`).
    HandVision,
    /// Voice / speech-to-text (Whisper or equivalent).
    Voice,
    /// Eye tracker (webcam, Tobii, headset).
    Gaze,
    /// Headset-resident producer (Quest 3, Vision Pro). Distinct from
    /// `HandVision` because the calibration profile is meaningfully
    /// different.
    Headset,
    /// EMG / wrist-band input (CTRL-Labs / Meta Neural Band, etc.).
    Emg,
    /// Biometric stream (heart-rate, GSR, respiration).
    Biometric,
    /// Posture / proximity sensor (presence, body angle, fatigue cues).
    Posture,
    /// Synthetic / test producer. Calibration is always
    /// [`CalibrationStatus::Synthetic`].
    Synthetic,
}

// --- Calibration -------------------------------------------------------------

/// Producer's self-assessment of trust at observation time.
///
/// **`Calibrated`** means the producer has run its calibration procedure
/// recently and has no reason to believe accuracy has degraded.
/// **`Uncalibrated`** is the conservative default: the producer either has
/// not been calibrated this session, or has detected drift / occlusion /
/// other failure mode. **`Synthetic`** marks tokens generated by tests or
/// replay, so confidence scoring can apply its own policy. **`Failed`**
/// marks tokens emitted while the producer is in a known-broken state, for
/// the few cases where it makes sense to emit anyway (e.g. fallback
/// rendering of last-known-good state).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum CalibrationStatus {
    /// Producer trusts its output.
    Calibrated,
    /// Producer is operating without recent calibration evidence. Pneuma
    /// applies the 20% confidence penalty.
    Uncalibrated,
    /// Test / replay token. Pneuma may apply its own policy.
    Synthetic,
    /// Producer is in a known-broken state; output is informational only.
    /// Pneuma must treat this as confidence ≈ 0.
    Failed,
}

impl CalibrationStatus {
    /// `true` if Pneuma should trust the value at face confidence.
    #[must_use]
    pub fn is_trusted(self) -> bool {
        matches!(self, Self::Calibrated)
    }

    /// `true` if the substrate considers the value usable at all
    /// (everything except [`CalibrationStatus::Failed`]).
    #[must_use]
    pub fn is_usable(self) -> bool {
        !matches!(self, Self::Failed)
    }
}

/// Detailed calibration metadata, attached to every [`crate::Tagged`] value.
///
/// Carries [`CalibrationStatus`] plus the wall-clock time of the producer's
/// last successful calibration, when known. Pneuma can use the staleness to
/// scale the confidence penalty.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Calibration {
    /// Coarse trust level.
    pub status: CalibrationStatus,
    /// Time of last successful calibration. `None` when the producer has
    /// never calibrated (e.g. a fresh `Synthetic` producer, or
    /// `Uncalibrated` at session start).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_calibrated_at: Option<Timestamp>,
}

impl Calibration {
    /// A `Calibrated` calibration with `last_calibrated_at` set to *now*.
    /// Convenience for producers that want to mint a fresh calibration in a
    /// single call.
    #[must_use]
    pub fn calibrated_now() -> Self {
        Self {
            status: CalibrationStatus::Calibrated,
            last_calibrated_at: Some(Timestamp::now()),
        }
    }

    /// An `Uncalibrated` calibration with no last-calibrated time. The
    /// most-conservative default.
    #[must_use]
    pub fn uncalibrated() -> Self {
        Self {
            status: CalibrationStatus::Uncalibrated,
            last_calibrated_at: None,
        }
    }

    /// A `Synthetic` calibration — for test data and replay tokens.
    #[must_use]
    pub fn synthetic() -> Self {
        Self {
            status: CalibrationStatus::Synthetic,
            last_calibrated_at: None,
        }
    }

    /// A `Failed` calibration — producer is in a known-broken state.
    #[must_use]
    pub fn failed() -> Self {
        Self {
            status: CalibrationStatus::Failed,
            last_calibrated_at: None,
        }
    }

    /// `true` if Pneuma should trust the value at face confidence. See
    /// [`CalibrationStatus::is_trusted`].
    #[must_use]
    pub fn is_trusted(&self) -> bool {
        self.status.is_trusted()
    }
}

// --- SensorMetadata ----------------------------------------------------------

/// Stable metadata about a sensor instance — id, kind, current calibration,
/// and a free-form display name.
///
/// Sensors include this in their stream's "meta" frame so consumers can
/// route by kind and degrade gracefully on calibration loss.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SensorMetadata {
    /// Sensor identity.
    pub id: SensorId,
    /// What this sensor observes.
    pub kind: SensorKind,
    /// Current calibration. May change over the life of the sensor;
    /// `SensorMetadata` is the producer's current snapshot.
    pub calibration: Calibration,
    /// Human-readable name for diagnostics. E.g. `"MediaPipe v0.10 (laptop
    /// webcam)"`. Free-form; consumers should not parse it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl SensorMetadata {
    /// Construct metadata for a freshly-minted, uncalibrated sensor.
    #[must_use]
    pub fn new(kind: SensorKind) -> Self {
        Self {
            id: SensorId::new(),
            kind,
            calibration: Calibration::uncalibrated(),
            display_name: None,
        }
    }

    /// Override the calibration. Used when the producer has just completed
    /// its calibration step.
    #[must_use]
    pub fn with_calibration(mut self, calibration: Calibration) -> Self {
        self.calibration = calibration;
        self
    }

    /// Attach a display name.
    #[must_use]
    pub fn with_display_name(mut self, name: impl Into<String>) -> Self {
        self.display_name = Some(name.into());
        self
    }
}
